
package com.customer.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerServiceImpl", targetNamespace = "http://impl.service.customer.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCustomer", targetNamespace = "http://impl.service.customer.com/", className = "com.customer.service.impl.AddCustomer")
    @ResponseWrapper(localName = "addCustomerResponse", targetNamespace = "http://impl.service.customer.com/", className = "com.customer.service.impl.AddCustomerResponse")
    public String addCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyCustomer", targetNamespace = "http://impl.service.customer.com/", className = "com.customer.service.impl.ModifyCustomer")
    @ResponseWrapper(localName = "modifyCustomerResponse", targetNamespace = "http://impl.service.customer.com/", className = "com.customer.service.impl.ModifyCustomerResponse")
    public String modifyCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCustomerId", targetNamespace = "http://impl.service.customer.com/", className = "com.customer.service.impl.DeleteCustomerId")
    @ResponseWrapper(localName = "deleteCustomerIdResponse", targetNamespace = "http://impl.service.customer.com/", className = "com.customer.service.impl.DeleteCustomerIdResponse")
    public String deleteCustomerId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.customer.service.impl.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerId", targetNamespace = "http://impl.service.customer.com/", className = "com.customer.service.impl.GetCustomerId")
    @ResponseWrapper(localName = "getCustomerIdResponse", targetNamespace = "http://impl.service.customer.com/", className = "com.customer.service.impl.GetCustomerIdResponse")
    public Customer getCustomerId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
